### ISSUE TITLE
[AWS] Create private hosted zone

### ISSUE THREAD

**Issue by anatolek** [Kv-126-DevOps/None#16]
Doc: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zone-private-creating.html

Create a private hosted zone and associate it with the default VPC https://eu-central-1.console.aws.amazon.com/vpc/home?region=eu-central-1#VpcDetails:VpcId=vpc-0d14e4956bccdc439

The name should be anything, but not long and understandable

**Comment by AlexPokatilov** [comment]
Done
